#!/usr/bin/env node

const dbUtils = require('../db/utils');

//const fs = require('fs');
//const file = '/tmp/jet_test.db';
//if (fs.existsSync(file)) fs.unlinkSync(file);

dbUtils.enableTestMode();

const timeout = 2 * 1000; // msec

return testChannelEvents();

function testChannelEvents() {
  dbUtils.recordChannelEvent('INACTIVE_CHANNEL', '177a96f52b7e80d73e41e4d724c52ff8133e82fc2930fa95dcfa2094122c303e', 0);
  dbUtils.recordChannelEvent('ACTIVE_CHANNEL', '0a5da800f865d65cfca158794f592acf57e608f9a5b54c5cb160d3cd11865c93', 1);
  setTimeout(() => {
    console.log(dbUtils.listChannelEvents({}));
  }, timeout);
}

function testActiveRebalance() {
  let ret = dbUtils.recordActiveRebalanceSync({
    from: '03eba3295492a69621a2501675b663c7051f6035b52f98f0e911475534f105e670',
    to: '035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226',
    amount: 500000,
    ppm: 650,
    mins: 30
  });
  console.log('inserted row:', ret);
  ret = dbUtils.recordActiveRebalanceSync({
    from: '0393a0f0312439b82d43ceb35af6f7a2a2d5a5aa71e461f66b418a77532db51c00',
    to: '035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226',
    amount: 1000000,
    ppm: 550,
    mins: 30
  });
  console.log('inserted row:', ret);
  console.log(dbUtils.listActiveRebalancesSync());

  dbUtils.deleteActiveRebalance(ret); // last row id
  setTimeout(() => {
    console.log(dbUtils.listActiveRebalancesSync());
  }, timeout);
}

function testNameValList() {
  dbUtils.recordValSync('aaaa', 1234);
  dbUtils.recordValSync('aaaa', 5678);
  dbUtils.recordValSync('bbbb', 4321);
  dbUtils.recordValSync('aaaa:bbbb', 1111);
  dbUtils.recordValSync('cccc:bbbb', 2222);
  dbUtils.recordValSync('aaaa:cccc', 3333);
  dbUtils.recordValSync('bbbb:cccc', 4444);
  console.log(dbUtils.getValSync('aaaa'));
  console.log(dbUtils.getValSync('bbbb'));
  console.log(dbUtils.getValSync('does not exist'));
  console.log(dbUtils.getValByFilterSync('aaaa:%'));
  console.log(dbUtils.getValByFilterSync('%:bbbb'));
  console.log(dbUtils.getValByFilterSync('%aaaa%'));
}

function testDb() {
  const name = 'testName';
  dbUtils.setPropSync(name, 12345);
  console.log(dbUtils.getPropSync(name));
  console.log(dbUtils.getPropAndDateSync(name));
  dbUtils.deleteProp(name);
  setTimeout(() => {
    console.log(dbUtils.getPropSync(name));
  }, 1000);
}

function testFeeHistory() {
  const nodeA = 'aaaaaaaa';
  const nodeB = 'bbbbbbbb';
  const chanA = 'cacacaca';
  const chanB = 'cbcbcbcb';
  dbUtils.recordFee({node:nodeA, chan:chanA, base:100});
  dbUtils.recordFee({node:nodeA, chan:chanA, ppm:999});
  dbUtils.recordFee({node:nodeA, chan:chanA, base:750, ppm:1999});
  dbUtils.recordFee({node:nodeB, chan:chanB, base:250});
  dbUtils.recordFee({node:nodeB, chan:chanB, ppm:899});
  dbUtils.recordFee({node:nodeB, chan:chanB, base:500, ppm:999});
  console.log(dbUtils.feeHistorySync({node:nodeA}));
  console.log(dbUtils.feeHistorySync({node:nodeB}));
  console.log(dbUtils.feeHistorySync({}));
}

dbUtils.recordTelegramMessageSync('hey there');
dbUtils.recordTelegramMessageSync('another hey there');
dbUtils.recordTelegramMessageSync('and another');
let list = dbUtils.fetchTelegramMessageSync();
console.log('telegram messages:', list);
let ids = [];
list.forEach(it => ids.push(it.id));
dbUtils.deleteTelegramMessages(ids);
console.log('deleted telegram messages');
setTimeout(() => {
  console.log('telegram messages:', dbUtils.fetchTelegramMessageSync());  
}, timeout);
console.log('doesnotexist:', dbUtils.getPropSync('doesnotexist'));
dbUtils.setPropSync('botChatId', '1234');
console.log('botChatId:', dbUtils.getPropAndDateSync('botChatId'));
console.log('botChatId:', dbUtils.getPropSync('botChatId'));
dbUtils.setPropSync('botChatId', '4321');
console.log('botChatId:', dbUtils.getPropAndDateSync('botChatId'));
console.log('botChatId:', dbUtils.getPropSync('botChatId'));

dbUtils.recordRebalanceAvoid('node_a', 'node_b', 750, 'avoid_a');
dbUtils.recordRebalanceAvoid('node_a', 'node_b', 750, 'avoid_b');
setTimeout(() => {
  console.log(dbUtils.listRebalanceAvoidSync('node_a', 'node_b', 750)); 
}, timeout);

function testHtlcs() {
  const genTimestamp = () => Date.now() * 1000000 + Math.floor(100000 + Math.random() * 900000);

  dbUtils.recordHtlc({
    incoming_channel_id: '775688960799080448',
    outgoing_channel_id: '770300254396219392',
    incoming_htlc_id: '8730',
    outgoing_htlc_id: '0',
    timestamp_ns: genTimestamp() + '',
    event_type: 'FORWARD',
    link_fail_event: {
      info: {
        incoming_timelock: 708016,
        outgoing_timelock: 707976,
        incoming_amt_msat: '200004799',
        outgoing_amt_msat: '200004598'
      },
      wire_failure: 'TEMPORARY_CHANNEL_FAILURE',
      failure_detail: 'INSUFFICIENT_BALANCE',
      failure_string: 'insufficient bandwidth to route htlc'
    },
    event: 'link_fail_event'
  }, true)

  dbUtils.recordHtlc({
    incoming_channel_id: '775688960799080448',
    outgoing_channel_id: '775647179368169473',
    incoming_htlc_id: '8730',
    outgoing_htlc_id: '0',
    timestamp_ns: genTimestamp() + '',
    event_type: 'FORWARD',
    link_fail_event: {
      info: {
        incoming_timelock: 708016,
        outgoing_timelock: 707976,
        incoming_amt_msat: '200004799',
        outgoing_amt_msat: '200004598'
      },
      wire_failure: 'TEMPORARY_CHANNEL_FAILURE',
      failure_detail: 'INSUFFICIENT_BALANCE',
      failure_string: 'insufficient bandwidth to route htlc'
    },
    event: 'link_fail_event'
  }, true)

  dbUtils.recordHtlc({
    incoming_channel_id: '754789443771498496',
    outgoing_channel_id: '770300254396219392',
    incoming_htlc_id: '1605',
    outgoing_htlc_id: '0',
    timestamp_ns: genTimestamp() + '',
    event_type: 'FORWARD',
    link_fail_event: {
      info: {
        incoming_timelock: 708091,
        outgoing_timelock: 708051,
        incoming_amt_msat: '261035380',
        outgoing_amt_msat: '260989706'
      },
      wire_failure: 'TEMPORARY_CHANNEL_FAILURE',
      failure_detail: 'INSUFFICIENT_BALANCE',
      failure_string: 'insufficient bandwidth to route htlc'
    },
    event: 'link_fail_event'
  }, true)

  dbUtils.recordHtlc({
    incoming_channel_id: '754789443771498496',
    outgoing_channel_id: '775647179368169473',
    incoming_htlc_id: '1605',
    outgoing_htlc_id: '0',
    timestamp_ns: genTimestamp() + '',
    event_type: 'FORWARD',
    link_fail_event: {
      info: {
        incoming_timelock: 708091,
        outgoing_timelock: 708051,
        incoming_amt_msat: '261035380',
        outgoing_amt_msat: '260989706'
      },
      wire_failure: 'TEMPORARY_CHANNEL_FAILURE',
      failure_detail: 'INSUFFICIENT_BALANCE',
      failure_string: 'insufficient bandwidth to route htlc'
    },
    event: 'link_fail_event'
  }, true)

  setTimeout(() => {
    const days = 2;
    console.log('over the past ' + days + ' days');
    console.log(dbUtils.listHtlcsSync({days:days})); 
    console.log('fromChan: 754789443771498496');
    console.log(dbUtils.listHtlcsSync({fromChan:'754789443771498496'})); 
    console.log('toChan: 770300254396219392');
    console.log(dbUtils.listHtlcsSync({toChan:'770300254396219392'})); 
  }, timeout);
}

function testRebalanceHistory() {
  const startDate = Date.now();
  dbUtils.recordRebalance(startDate, 'node_a', 'node_b', 1000000, 350000, 350);
  dbUtils.recordRebalance(startDate, 'node_a', 'node_c', 2000000, 550000, 675);
  dbUtils.recordRebalance(startDate, 'node_a', 'node_c', 2000000, 550000, 675, 'regular');
  dbUtils.recordRebalance(startDate, 'node_a', 'node_c', 2000000, 550000, 675, 'missed');
  dbUtils.recordRebalanceFailure(startDate, 'node_a', 'node_c', 1000000, 'ops', 550, 950);
  dbUtils.recordRebalanceFailure(startDate, 'node_a', 'node_c', 1000000, 'ops', 550, 950, 'forward');
  dbUtils.recordRebalanceFailure(startDate, 'node_a', 'node_c', 2000000, 'ops again', 675);
  dbUtils.recordRebalanceFailure(startDate, 'node_a', 'node_c', 2000000, 'ops again', 675, 0, 'missed');
  setTimeout(() => {
    console.log(dbUtils.listRebalancesSync()); 
  }, timeout);
}
