#!/usr/bin/env node

global.testModeOn = true;

const lndClient = require('../api/connect');
const {forwardHistorySync} = require('../lnd-api/utils');

console.log(forwardHistorySync(lndClient, 5 * 60 * 60));
