#!/usr/bin/env node

global.testModeOn = true;

const importLazy = require('import-lazy')(require);
const lndClient = importLazy('../api/connect');
const {isLndAlive} = importLazy('../lnd-api/utils');

console.log('lnd alive:', isLndAlive(lndClient));
