#!/usr/bin/env node

const {listActiveRebalancesSync} = require('../api/utils');
const {listActiveRebalancesFormattedSync} = require('../api/utils');

console.table(listActiveRebalancesSync());
console.table(listActiveRebalancesFormattedSync());
