#!/usr/bin/env node

const {listRebalancesSync} = require('../db/utils');
const {rebalanceHistoryConsolidated} = require('../api/utils');

//let history = listRebalancesSync(60 * 60);
//console.log(history);
let map = rebalanceHistoryConsolidated(4);
console.log(map);
