#!/usr/bin/env node

// rebalance process launcher, used by auto-rebalancer
// do not call directly

const importLazy = require('import-lazy')(require);
const rebalanceApi = importLazy('../../api/rebalance');

const pref = 'rebalance-proc:';
if (!process.argv || process.argv.length <= 2) {
  return console.error(pref, 'missing arguments');
}

let from, to, amount, ppm, type;

let args = process.argv.slice(2);
for(i = 0; i < args.length; i++) {
  if (args[i].indexOf('--from') >= 0) {
    from = args[i + 1];
  } else if (args[i].indexOf('--to') >= 0) {
    to = args[i + 1];
  } else if (args[i].indexOf('--amount') >= 0) {
    amount = parseInt(args[i + 1]);
  } else if (args[i].indexOf('--ppm') >= 0) {
    ppm = parseInt(args[i + 1]);
  } else if (args[i].indexOf('--type') >= 0) {
    type = args[i + 1];
  } else {
    console.error(pref, 'unknown argument:', args[i]);
  }
  i++;
}

if (!from || !to || !amount || !ppm || !type) {
  return console.error(pref, 'from, to, amount, ppm, and type are mandatory');
}

rebalanceApi({
  from: from,
  to: to,
  amount: amount,
  ppm: ppm,
  type: type
})
