#!/usr/bin/env node

// generates initial ./api/config.json; run once after install

const fs = require('fs');

const FILE = __dirname + '/../api/config.json';

const data = 
'{\n\
  "avoid": [\n\
  ],\n\
  "macaroonPath": "/home/umbrel/umbrel/lnd/data/chain/bitcoin/mainnet/admin.macaroon",\n\
  "tlsCertPath": "/home/umbrel/umbrel/lnd/tls.cert",\n\
  "debugMode": false,\n\
  "rebalancer": {\n\
    "maxTime": 30,\n\
    "maxPpm": 650,\n\
    "maxAutoPpm": 500,\n\
    "maxInstances": 10,\n\
    "maxPendingHtlcs": 4,\n\
    "enforceMaxPpm": false,\n\
    "exclude": [\n\
    ]\n\
  }\n\
}\n';

if (fs.existsSync(FILE)) return;  // don't overwrite config
fs.writeFile(FILE, data, err => {
  if (err) {
    return console.error(err)
  }
})
