#!/usr/bin/env node

// generates initial ./api/config.json; run once after install

const fs = require('fs');

const FILE = __dirname + '/../api/config.json';

const data = 
'{\n\
  "avoid": [\n\
  ],\n\
  "max_ppm": 650,\n\
  "adminMacaroonPath": "/home/umbrel/umbrel/lnd/data/chain/bitcoin/mainnet/admin.macaroon",\n\
  "tlsCertPath": "/home/umbrel/umbrel/lnd/tls.cert",\n\
  "debugMode": false\n\
}';

if (fs.existsSync(FILE)) return;  // don't overwrite config
fs.writeFile(FILE, data, err => {
  if (err) {
    return console.error(err)
  }
})
